"""Enhanced donor signup

Revision ID: ba83396b7f8d
Revises: 83d03ad3cd42
Create Date: 2025-11-29 23:35:40.073819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba83396b7f8d'
down_revision: Union[str, Sequence[str], None] = '83d03ad3cd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.add_column('donor_profiles', sa.Column('state_city', sa.String(length=100), nullable=True))
    op.add_column('donor_profiles', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('donor_profiles', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('donor_profiles', sa.Column('preferred_causes', sa.Text(), nullable=True))
    op.add_column('donor_profiles', sa.Column('preferred_ngo_types', sa.Text(), nullable=True))
    op.add_column('donor_profiles', sa.Column('monthly_donation_goal', sa.Float(), nullable=True))
    op.add_column('donor_profiles', sa.Column('preferred_currency', sa.String(length=10), nullable=False, server_default='ADA'))
    op.add_column('donor_profiles', sa.Column('wallet_address', sa.String(length=255), nullable=True))
    op.add_column('donor_profiles', sa.Column('wallet_provider', sa.String(length=50), nullable=True))
    op.add_column('donor_profiles', sa.Column('wallet_connected', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('donor_profiles', sa.Column('consent_onchain_storage', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('donor_profiles', 'interests')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'full_name')
    op.add_column('donor_profiles', sa.Column('interests', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('donor_profiles', 'consent_onchain_storage')
    op.drop_column('donor_profiles', 'wallet_connected')
    op.drop_column('donor_profiles', 'wallet_provider')
    op.drop_column('donor_profiles', 'wallet_address')
    op.drop_column('donor_profiles', 'preferred_currency')
    op.drop_column('donor_profiles', 'monthly_donation_goal')
    op.drop_column('donor_profiles', 'preferred_ngo_types')
    op.drop_column('donor_profiles', 'preferred_causes')
    op.drop_column('donor_profiles', 'profile_picture_url')
    op.drop_column('donor_profiles', 'phone_number')
    op.drop_column('donor_profiles', 'state_city')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
